### ISSUE TITLE
`npm run debug `错误

### ISSUE THREAD

**Issue by FrancisKong** [matthew-sun/redux-example#4]
使用`npm run debug` 命令报错
错误提示如下：
![qq 20151222145815](https://cloud.githubusercontent.com/assets/7656698/11949661/6ecb1aaa-a8bc-11e5-9756-fe2dca3d90a2.png)

**Comment by georgezouq** [comment]
我也报这个错误 请问是怎么解决的？？

**Comment by matthew-sun** [comment]
windows 命令行设置环境变量是 set DEBUG=true 这样子
命令可以改成

set DEBUG=true &&  node server.js

**Comment by georgezouq** [comment]
@matthew-sun  我是使用 npm start 的时候报错的

**Comment by matthew-sun** [comment]
@a757375927 npm依赖都安装好了吗

**Comment by georgezouq** [comment]
@matthew-sun  npm install 的时候会有这个问题 ![qq 20160324140931](https://cloud.githubusercontent.com/assets/5990860/14009755/1770cd7a-f1ca-11e5-9600-05ce6758ce36.png)

**Comment by matthew-sun** [comment]
https://github.com/luqin/blog/issues/9

**Comment by georgezouq** [comment]
@matthew-sun 还是不行  还是报错

**Comment by RealAmissio** [comment]
`Last login: Sun Jun 19 16:16:53 on ttys002
Ami:~ amissio$ cd/Users/amissio/Downloads/redux-example-master
-bash: cd/Users/amissio/Downloads/redux-example-master: No such file or directory
Ami:~ amissio$ cd /Users/amissio/Downloads/redux-example-master
Ami:redux-example-master amissio$ npm start

> redux--example@1.0.1 start /Users/amissio/Downloads/redux-example-master
> node server.js

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server.__dirname.Server.Server._listen2 (net.js:1230:14)
    at listen (net.js:1266:10)
    at net.js:1375:9
    at GetAddrInfoReqWrap.asyncCallback [as callback](dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:82:10)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! redux--example@1.0.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the redux--example@1.0.1 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the redux--example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs redux--example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls redux--example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/amissio/Downloads/redux-example-master/npm-debug.log`
@matthew-sun 请问这个怎么解决啊

**Comment by kaerhasnoballs** [comment]
@matthew-sun 我npm install的时候报错，错误如下：
![upload](https://cloud.githubusercontent.com/assets/5338207/17956695/43a2f428-6abe-11e6-8e95-514908736fd7.png)
